version: '3'
services:
  webdav:
    build: .
    ports:
      - "80:80"
    volumes:
      - "/mnt/movies:/media"
    restart: unless-stopped
    #environment:
    #  USERNAME: user
    #  PASSWORD: passwd
